name: Pail
main: me.escapeNT.pail.Pail
version: ${version}
author: escape
website: http://dev.bukkit.org/server-mods/pail/
description: A GUI designed specifically for bukkit allowing admins to both manage the server as well as compatable plugins.
load: startup
commands:
  Pail:
    description: Opens the main Pail window.
    usage: /<command>